
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    # HTTP SERVER
    server {
        listen       80;
        server_name  localhost;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

	
    # CERTIFICATE LOGGING
    log_format client_cert '[$time_local] CLIENT CERTIFICATE - $ssl_client_raw_cert';
    log_format client_issuer_dn '[$time_local] CLIENT ISSUER DN - $ssl_client_i_dn';
    log_format client_subject_dn '[$time_local] CLIENT SUBJECT DN - $ssl_client_s_dn';
    log_format client_serial '[$time_local] CLIENT SERIAL NUM - $ssl_client_serial';
    log_format client_sigalg '[$time_local] CLIENT SIGNATURE ALGO - $ssl_client_sigalg';
    log_format client_end '[$time_local] CLIENT END - $ssl_client_v_end';
    log_format client_start '[$time_local] CLIENT START - $ssl_client_v_start';
    log_format client_verify '[$time_local] CLIENT VERIFY - $ssl_client_verify';


    # HTTPS server
    server {
        listen       443 ssl;
        server_name  localhost;

	# server's certificates
	# classical - server.pem, server.key, pass.txt
	# pqc - pqc_server.pem, pqc_server_unencrypted.key, pqc_pass.txt
        ssl_certificate      server_cert/pqc_server.pem;
        ssl_certificate_key  server_cert/pqc_server_unencrypted.key;
	ssl_password_file    server_cert/pqc_pass.txt;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

	# ssl_conf_command Groups MLKEM768;

    	ssl_protocols TLSv1.3;

	ssl_client_certificate client_cert.pem;
	ssl_verify_client optional;

        location / {
            root   html;
            index  index.html index.htm;
        }
	
	access_log logs/access.log client_cert;
	access_log logs/access.log client_issuer_dn;
	access_log logs/access.log client_subject_dn;
	access_log logs/access.log client_serial;
	access_log logs/access.log client_sigalg;
	access_log logs/access.log client_end;
	access_log logs/access.log client_start;
	access_log logs/access.log client_verify;
	
    }

}
